name: Extract and release build artifact

# Note: This event will only trigger a workflow run
# if the workflow file is on the default branch
# - So we need to run this workflow explicitly again
# after the container are pushed to the registry
#on:
#  workflow_run:
#    workflows: ["Build and release container"]
#    branches: '**'
#    types:
#      - completed

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  workflow_dispatch:

jobs:
  extract-artifacts:
    uses: bbusse/github-workflows/.github/workflows/container-extract-artifacts.yml@dev
    with:
      image: ghcr.io/bbusse/swayvnc-build:latest
      wait_for_job: container-build-push
      release: true
      release_tag: latest
      release_name: wayvnc
      artifacts: |
        [
          {"path": "home/build/wayvnc-0.10.0-r1.apk",       "name": "wayvnc-0.10.0-r1-x86_64.apk",       "platform": "linux/amd64"},
          {"path": "home/build/neatvnc-1.0.0-r0.apk",       "name": "neatvnc-1.0.0-r0-x86_64.apk",       "platform": "linux/amd64"},
          {"path": "home/build/neatvnc-dev-1.0.0-r0.apk",   "name": "neatvnc-dev-1.0.0-r0-x86_64.apk",   "platform": "linux/amd64"},
          {"path": "home/build/wayvnc-0.10.0-r1.apk",       "name": "wayvnc-0.10.0-r1-aarch64.apk",      "platform": "linux/arm64"},
          {"path": "home/build/neatvnc-1.0.0-r0.apk",       "name": "neatvnc-1.0.0-r0-aarch64.apk",      "platform": "linux/arm64"},
          {"path": "home/build/neatvnc-dev-1.0.0-r0.apk",   "name": "neatvnc-dev-1.0.0-r0-aarch64.apk",  "platform": "linux/arm64"}
        ]
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
